### ISSUE TITLE
UX: having many cluster labels breaks the UI layout

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#913]
Would be nice to have the UI that can scale well when having lots of labels.

**Comment by Unix4ever** [comment]
<img width="1445" alt="Image" src="https://github.com/user-attachments/assets/491f9828-9900-4e2f-a64c-c0353880e516" />

**Comment by Slessi** [comment]
@Unix4ever is this resolved now with #1516?

**Comment by Unix4ever** [comment]
Not resolved, as this is `Clusters` page, which wasn't changed. We still need the UX rework done here.

**Comment by AlexB-Shorepine** [comment]
Possible solution for that problem is presented in Figma:
[direct link to figma page](https://www.figma.com/design/4qvWHbfWdFKcDc29wPRn3l/Sidero-UI?node-id=3928-35107&t=HJVHnUSQWYvWeRH5-1)

**Comment by Slessi** [comment]
@AlexB-Shorepine Is the proposed solution from figma max length and truncation? Or is there also something else that I am missing?

**Comment by AlexB-Shorepine** [comment]
@Slessi as concluded today, we start with max length, truncation and tooltips for longer labels and we test it. Afterwards if that is not enough we shift row of labels to a different position
